import Link from 'next/link'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import {
  ArrowUpRight,
  ChevronDown,
  Database,
  Dna,
  Globe2,
  MapPinned,
} from 'lucide-react'
import { buildMapHref } from './map/types'

type LandingStats = {
  generatedAt: string
  kpis: {
    speciesWithAssemblies: number
    speciesWithGeography: number
    speciesWithGeographyPct: number
    totalInstitutes: number
    institutesWithCoordinates: number
    institutesWithCoordinatesPct: number
    speciesInAtlas: number
    speciesWithInstituteArc: number
    speciesWithInstituteArcPct: number
  }
  pipeline: {
    step: number
    title: string
    description: string
  }[]
  disclaimers: {
    id: string
    text: string
  }[]
}

/**
 * Read the build-time landing-stats.json (generated by scripts/build_landing_stats.py)
 * so the landing page reflects the live dataset. Falls back to null if missing.
 */
async function getLandingStats(): Promise<LandingStats | null> {
  try {
    const filePath = path.join(process.cwd(), 'public', 'data', 'landing-stats.json')
    const raw = await readFile(filePath, 'utf-8')
    return JSON.parse(raw) as LandingStats
  } catch {
    return null
  }
}

const QUICK_START_LINKS = [
  { label: 'Latin America', href: buildMapHref({ customId: 'latin-america' }) },
  { label: 'Africa', href: buildMapHref({ continent: 'Africa' }) },
  { label: 'Spain', href: buildMapHref({ country: 'Spain' }) },
  { label: 'UK', href: buildMapHref({ country: 'United Kingdom' }) },
]

/** Short chart captions for pipeline nodes (avoids long prose from landing-stats). */
const PIPELINE_SHORT_COPY: Record<number, string> = {
  1: 'NCBI assemblies, BioSample locality, species taxids.',
  2: 'ENA lineages rolled up for map filters.',
  3: 'Submitter strings matched to ROR country and coordinates.',
  4: 'One row per species written to the map parquet.',
}

function formatPct(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1)
}

export default async function Page() {
  const stats = await getLandingStats()
  const pipeline = stats?.pipeline ?? []
  const disclaimers = stats?.disclaimers
  const kpis = stats?.kpis
  const speciesWithAssemblies = kpis?.speciesWithAssemblies ?? 29410
  const speciesWithGeography = kpis?.speciesWithGeography ?? 23237
  const speciesWithGeographyPct = kpis?.speciesWithGeographyPct ?? 79.0
  const totalInstitutes = kpis?.totalInstitutes ?? 5697
  const institutesWithCoordinates = kpis?.institutesWithCoordinates ?? 3619
  const institutesWithCoordinatesPct = kpis?.institutesWithCoordinatesPct ?? 63.5
  const speciesInAtlas = kpis?.speciesInAtlas ?? 23237
  const speciesWithInstituteArc = kpis?.speciesWithInstituteArc ?? 17784
  const speciesWithInstituteArcPct = kpis?.speciesWithInstituteArcPct ?? 76.5

  return (
    <main className="landing-shell">
      <nav className="top-nav landing-nav">
        <Link href="/" className="wordmark">
          GenoFlow<span className="wordmark-dot">.</span>
        </Link>
        {process.env.NODE_ENV !== 'production' && <span className="mock-badge">MVP</span>}
        <div className="nav-links">
          <a href="#about">About</a>
          <a href="#pipeline">Pipeline</a>
          <Link href="/map" className="nav-map-link">
            Open the map <ArrowUpRight size={14} aria-hidden="true" />
          </Link>
        </div>
      </nav>
      <section className="landing-hero">
        <div className="hero-copy">
          <p className="eyebrow">Eukaryotes</p>
          <h1>
            GenoFlow<span className="wordmark-dot">.</span>
          </h1>
          <p className="hero-subcopy">
            Tracking where species are collected against where their genomes are submitted.
          </p>
          <div className="hero-actions">
            <Link href="/map" className="button button-primary">
              Explore the map <ArrowUpRight size={17} aria-hidden="true" />
            </Link>
            <a href="#about" className="text-button">
              How to read this <ChevronDown size={16} aria-hidden="true" />
            </a>
          </div>
          <nav className="quick-start-links" aria-label="Quick-start map views">
            <span className="eyebrow">Jump to a region</span>
            <div className="quick-start-row">
              {QUICK_START_LINKS.map((link) => (
                <Link key={link.label} href={link.href} className="quick-start-link">
                  {link.label} <ArrowUpRight size={12} aria-hidden="true" />
                </Link>
              ))}
            </div>
          </nav>
        </div>
      </section>
      <section className="landing-kpis" aria-label="Dataset overview">
        <div className="landing-kpi-grid">
          <article className="landing-kpi-card">
            <span>Species with geography</span>
            <b>{speciesWithGeography.toLocaleString()}</b>
            <small>
              of {speciesWithAssemblies.toLocaleString()} assemblies ·{' '}
              {formatPct(speciesWithGeographyPct)}%
            </small>
          </article>
          <article className="landing-kpi-card">
            <span>Institutes geocoded</span>
            <b>{institutesWithCoordinates.toLocaleString()}</b>
            <small>
              of {totalInstitutes.toLocaleString()} institutes ·{' '}
              {formatPct(institutesWithCoordinatesPct)}%
            </small>
          </article>
          <article className="landing-kpi-card">
            <span>Species with full flow</span>
            <b>{speciesWithInstituteArc.toLocaleString()}</b>
            <small>
              of {speciesInAtlas.toLocaleString()} atlas species ·{' '}
              {formatPct(speciesWithInstituteArcPct)}%
            </small>
          </article>
        </div>
      </section>
      <section className="about-section" id="about">
        <div className="section-intro">
          <h2>Two maps, one species.</h2>
          <p>Every record carries two geographies. GenoFlow puts them back in the same frame.</p>
        </div>
        <div className="reading-grid">
          <article className="reading-card">
            <div className="card-icon amber-icon">
              <MapPinned size={18} />
            </div>
            <span className="card-kicker">01 / Collected</span>
            <h3>Where the specimen entered the record.</h3>
            <p>Locality and country recorded at the time of collection.</p>
          </article>
          <article className="reading-card">
            <div className="card-icon blue-icon">
              <Database size={18} />
            </div>
            <span className="card-kicker">02 / Submitted</span>
            <h3>Where the assembly was deposited.</h3>
            <p>
              Institution and country associated with the genome assembly. A proxy for where
              computation and curation happened.
            </p>
          </article>
          <article className="reading-card flow-card">
            <div className="card-icon flow-icon">
              <Dna size={18} />
            </div>
            <span className="card-kicker">03 / Flow</span>
            <h3>The distance between them.</h3>
            <p>
              The line connecting where a species was collected and where its genome was submitted.
            </p>
            <Link href="/map" className="card-link">
              See the flow <ArrowUpRight size={15} />
            </Link>
          </article>
        </div>
      </section>
      {pipeline.length > 0 && (
        <section className="about-section pipeline-section" id="pipeline">
          <div className="section-intro">
            <h2>From GenBank to the map.</h2>
            <p>
              Assemblies and taxonomy first, then ROR geography, then one flow per species.
            </p>
          </div>
          <ol className="pipeline-flow">
            {pipeline.map((step) => (
              <li key={step.step} className="pipeline-node">
                <span className="pipeline-step">{String(step.step).padStart(2, '0')}</span>
                <h3>{step.title}</h3>
                <p>{PIPELINE_SHORT_COPY[step.step] ?? step.description}</p>
              </li>
            ))}
          </ol>
        </section>
      )}
      <footer className="landing-footer">
        <div>
          <Globe2 size={16} />
          <span>GenoFlow / field notes</span>
        </div>
        {disclaimers && disclaimers.length > 0 ? (
          <ul className="disclaimer-list">
            {disclaimers.map((item) => (
              <li key={item.id}>
                <strong>
                  {item.id === 'institute-concentration'
                    ? 'Institute concentration:'
                    : item.id === 'missing-geography'
                      ? 'Missing geography:'
                      : 'Reading the caveat:'}
                </strong>{' '}
                {item.text}
              </li>
            ))}
          </ul>
        ) : (
          <p>
            <strong>Reading the caveat:</strong> geo_loc_name is sample collection, not always wild
            origin. Submitter country is a proxy for where assembled, not the sequencer. Data
            sourced from INSDC / ENA eukaryote assemblies.
          </p>
        )}
      </footer>
    </main>
  )
}
