export type Hemisphere = 'south' | 'north'
export type Flow = 'south-north' | 'south-south' | 'north-north' | 'north-south'

export type Species = {
  id: string
  scientificName: string
  commonName: string
  taxon: string
  kingdom: string
  className: string
  order: string
  collection: { locality: string; country: string; lat: number; lng: number; year: number; hemisphere: Hemisphere; globalSouth: boolean; habitat: string }
  submitter: { institution: string; city: string; country: string; lat: number; lng: number; globalNorth: boolean; name: string }
  assembly: { accession: string; level: 'chromosome' | 'scaffold'; year: number; sizeMb: number }
  flow: Flow
}

export const species: Species[] = [
  { id: 'jaguar', scientificName: 'Panthera onca', commonName: 'Jaguar', taxon: 'NCBI: 9627', kingdom: 'Animalia', className: 'Mammalia', order: 'Carnivora', collection: { locality: 'Rio Negro basin, Amazonas', country: 'Brazil', lat: -3.1, lng: -60.0, year: 2021, hemisphere: 'south', globalSouth: true, habitat: 'terra firme rainforest' }, submitter: { institution: 'Broad Institute', city: 'Cambridge', country: 'United States', lat: 42.37, lng: -71.11, globalNorth: true, name: 'M. Alvarez' }, assembly: { accession: 'GCA_031482715.1', level: 'chromosome', year: 2023, sizeMb: 2390 }, flow: 'south-north' },
  { id: 'baobab', scientificName: 'Adansonia grandidieri', commonName: "Grandidier's baobab", taxon: 'NCBI: 69190', kingdom: 'Plantae', className: 'Magnoliopsida', order: 'Malvales', collection: { locality: 'Avenue of the Baobabs, Menabe', country: 'Madagascar', lat: -20.25, lng: 44.42, year: 2019, hemisphere: 'south', globalSouth: true, habitat: 'dry deciduous forest' }, submitter: { institution: 'Royal Botanic Gardens, Kew', city: 'London', country: 'United Kingdom', lat: 51.48, lng: -0.29, globalNorth: true, name: 'A. Mwangi' }, assembly: { accession: 'GCA_028451902.1', level: 'scaffold', year: 2022, sizeMb: 1280 }, flow: 'south-north' },
  { id: 'peacock', scientificName: 'Afropavo congensis', commonName: 'Congo peacock', taxon: 'NCBI: 31868', kingdom: 'Animalia', className: 'Aves', order: 'Galliformes', collection: { locality: 'Ituri Forest, North Kivu', country: 'Democratic Republic of the Congo', lat: 1.67, lng: 29.0, year: 2020, hemisphere: 'north', globalSouth: true, habitat: 'lowland rainforest' }, submitter: { institution: 'Royal Museum for Central Africa', city: 'Tervuren', country: 'Belgium', lat: 50.82, lng: 4.52, globalNorth: true, name: 'E. Van den Berg' }, assembly: { accession: 'GCA_030119472.1', level: 'chromosome', year: 2024, sizeMb: 1120 }, flow: 'south-north' },
  { id: 'frog', scientificName: 'Telmatobius culeus', commonName: 'Titicaca water frog', taxon: 'NCBI: 71796', kingdom: 'Animalia', className: 'Amphibia', order: 'Anura', collection: { locality: 'Lake Titicaca, Puno', country: 'Peru', lat: -15.84, lng: -69.43, year: 2018, hemisphere: 'south', globalSouth: true, habitat: 'high-altitude freshwater' }, submitter: { institution: 'Senckenberg Research Institute', city: 'Frankfurt', country: 'Germany', lat: 50.12, lng: 8.67, globalNorth: true, name: 'L. Hoffmann' }, assembly: { accession: 'GCA_027558316.1', level: 'scaffold', year: 2021, sizeMb: 1780 }, flow: 'south-north' },
  { id: 'protea', scientificName: 'Protea cynaroides', commonName: 'King protea', taxon: 'NCBI: 110167', kingdom: 'Plantae', className: 'Magnoliopsida', order: 'Proteales', collection: { locality: 'Hottentots Holland Mountains', country: 'South Africa', lat: -34.08, lng: 18.85, year: 2020, hemisphere: 'south', globalSouth: true, habitat: 'fynbos shrubland' }, submitter: { institution: 'Wageningen University', city: 'Wageningen', country: 'Netherlands', lat: 51.99, lng: 5.66, globalNorth: true, name: 'R. de Vries' }, assembly: { accession: 'GCA_029776201.1', level: 'chromosome', year: 2023, sizeMb: 1320 }, flow: 'south-north' },
  { id: 'manatee', scientificName: 'Trichechus inunguis', commonName: 'Amazonian manatee', taxon: 'NCBI: 9777', kingdom: 'Animalia', className: 'Mammalia', order: 'Sirenia', collection: { locality: 'Mamirauá Reserve, Amazonas', country: 'Brazil', lat: -3.05, lng: -64.8, year: 2022, hemisphere: 'south', globalSouth: true, habitat: 'floodplain lake' }, submitter: { institution: 'Instituto Nacional de Pesquisas da Amazônia', city: 'Manaus', country: 'Brazil', lat: -3.12, lng: -60.02, globalNorth: false, name: 'J. Pereira' }, assembly: { accession: 'GCA_032118450.1', level: 'chromosome', year: 2024, sizeMb: 3050 }, flow: 'south-south' },
  { id: 'raven', scientificName: 'Corvus corax', commonName: 'Common raven', taxon: 'NCBI: 8076', kingdom: 'Animalia', className: 'Aves', order: 'Passeriformes', collection: { locality: 'Abisko National Park', country: 'Sweden', lat: 68.35, lng: 18.82, year: 2017, hemisphere: 'north', globalSouth: false, habitat: 'subarctic birch woodland' }, submitter: { institution: 'Uppsala University', city: 'Uppsala', country: 'Sweden', lat: 59.86, lng: 17.64, globalNorth: true, name: 'K. Lindström' }, assembly: { accession: 'GCA_021442115.2', level: 'chromosome', year: 2020, sizeMb: 1110 }, flow: 'north-north' },
  { id: 'moose', scientificName: 'Alces alces', commonName: 'Eurasian moose', taxon: 'NCBI: 9855', kingdom: 'Animalia', className: 'Mammalia', order: 'Artiodactyla', collection: { locality: 'Luleå archipelago', country: 'Sweden', lat: 65.58, lng: 22.15, year: 2016, hemisphere: 'north', globalSouth: false, habitat: 'boreal forest' }, submitter: { institution: 'University of Helsinki', city: 'Helsinki', country: 'Finland', lat: 60.17, lng: 24.94, globalNorth: true, name: 'T. Korhonen' }, assembly: { accession: 'GCA_019376492.2', level: 'chromosome', year: 2019, sizeMb: 2650 }, flow: 'north-north' },
  { id: 'lemur', scientificName: 'Lemur catta', commonName: 'Ring-tailed lemur', taxon: 'NCBI: 9447', kingdom: 'Animalia', className: 'Mammalia', order: 'Primates', collection: { locality: 'Berenty Reserve, Anosy', country: 'Madagascar', lat: -25.02, lng: 46.3, year: 2019, hemisphere: 'south', globalSouth: true, habitat: 'gallery forest' }, submitter: { institution: 'University of Cape Town', city: 'Cape Town', country: 'South Africa', lat: -33.92, lng: 18.42, globalNorth: false, name: 'N. Jacobs' }, assembly: { accession: 'GCA_026449818.1', level: 'scaffold', year: 2022, sizeMb: 3050 }, flow: 'south-south' },
  { id: 'orchid', scientificName: 'Dracula simia', commonName: 'Monkey face orchid', taxon: 'NCBI: 155274', kingdom: 'Plantae', className: 'Liliopsida', order: 'Asparagales', collection: { locality: 'Andean cloud forest, Pichincha', country: 'Ecuador', lat: -0.15, lng: -78.6, year: 2021, hemisphere: 'south', globalSouth: true, habitat: 'montane cloud forest' }, submitter: { institution: 'University of São Paulo', city: 'São Paulo', country: 'Brazil', lat: -23.55, lng: -46.63, globalNorth: false, name: 'C. Rocha' }, assembly: { accession: 'GCA_031902671.1', level: 'scaffold', year: 2024, sizeMb: 920 }, flow: 'south-south' },
  { id: 'eagle', scientificName: 'Aquila chrysaetos', commonName: 'Golden eagle', taxon: 'NCBI: 8962', kingdom: 'Animalia', className: 'Aves', order: 'Accipitriformes', collection: { locality: 'Highlands, Cairngorms', country: 'United Kingdom', lat: 57.08, lng: -3.61, year: 2018, hemisphere: 'north', globalSouth: false, habitat: 'montane heath' }, submitter: { institution: 'University of Edinburgh', city: 'Edinburgh', country: 'United Kingdom', lat: 55.95, lng: -3.19, globalNorth: true, name: 'S. MacLeod' }, assembly: { accession: 'GCA_024511903.1', level: 'chromosome', year: 2021, sizeMb: 1210 }, flow: 'north-north' },
]

export const filters = ['All species', 'Mammals', 'Birds', 'Plants', 'Fungi'] as const
export type SpeciesFilter = (typeof filters)[number]
export const matchesFilter = (item: Species, filter: SpeciesFilter) => filter === 'All species' || (filter === 'Mammals' ? item.className === 'Mammalia' : filter === 'Birds' ? item.className === 'Aves' : filter === 'Plants' ? item.kingdom === 'Plantae' : item.kingdom === 'Fungi')
export const flowLabel = (flow: Flow) => ({ 'south-north': 'South → North', 'south-south': 'South → South', 'north-north': 'North → North', 'north-south': 'North → South' })[flow]
export const project = (lat: number, lng: number) => ({ x: ((lng + 180) / 360) * 1000, y: ((90 - lat) / 180) * 480 })
export const formatCoord = (value: number, axis: 'lat' | 'lng') => `${Math.abs(value).toFixed(2)}°${axis === 'lat' ? (value >= 0 ? 'N' : 'S') : value >= 0 ? 'E' : 'W'}`

export const collectionCount = species.length
export const southNorthCount = species.filter((item) => item.flow === 'south-north').length
export const northCount = species.filter((item) => item.flow === 'north-north').length

export default species
